repos:
- repo: https://github.com/ambv/black
  rev: 21.12b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.930
  hooks:
  - id: mypy
    args: [--no-strict-optional, --ignore-missing-imports]
    additional_dependencies:
      - types-attrs
